package com.dododial.phone.database
object ClientDBConstants {
    const val CHANGELOG_TYPE_CONTACT_INSERT = "INSC"
    const val CHANGELOG_TYPE_CONTACT_UPDATE = "UPDC"
    const val CHANGELOG_TYPE_CONTACT_DELETE = "DELC"
    const val CHANGELOG_TYPE_CONTACT_NUMBER_INSERT = "INSN"
    const val CHANGELOG_TYPE_CONTACT_NUMBER_UPDATE = "UPDN"
    const val CHANGELOG_TYPE_CONTACT_NUMBER_DELETE = "DELN"
    const val CHANGELOG_TYPE_INSTANCE_INSERT = "INSI"
    const val CHANGELOG_TYPE_INSTANCE_DELETE = "DELI"

    const val RESPONSE_OK = 0
    const val RESPONSE_ERROR = 1
}